// Generated by CoffeeScript 1.10.0
var TimelineLite, TweenLite, TweenMax;

if (TweenMax === undefined) {
  TweenMax = false;
}

if (TimelineLite === undefined) {
  TimelineLite = false;
}

if (TweenLite === undefined) {
  TweenLite = false;
}

(function(window, TweenLite, TweenMax, TimelineLite) {
  var PrettyGSAP, _animate, _mergeObjs, _registerAnimation, _setAnimator, _setStartAfter, _startRegisteredAnimations, _ucfirst, animate;
  _mergeObjs = function(obj1, obj2) {
    var attrName;
    for (attrName in obj2) {
      obj1[attrName] = obj2[attrName];
    }
  };
  _ucfirst = function(string) {
    return string.charAt(0).toUpperCase() + string.slice(1);
  };
  _setStartAfter = function() {
    return this._currentAnimation.startAfter1 = this._currentAnimation.startAfter2;
  };
  _setAnimator = function(animator) {
    return this._gsapObj = animator;
  };
  _registerAnimation = function() {
    var method, parameters;
    method = this._currentAnimation.methodName;
    parameters = [];
    parameters[0] = this._currentAnimation.el;
    parameters[1] = this._currentAnimation.duration;
    if (method === 'from') {
      parameters[2] = this._currentAnimation.fromProps;
      _mergeObjs(parameters[2], this._currentAnimation.config);
    }
    if (method === 'to') {
      parameters[2] = this._currentAnimation.toProps;
      _mergeObjs(parameters[2], this._currentAnimation.config);
    }
    if (method === 'fromTo') {
      parameters[2] = this._currentAnimation.fromProps;
      parameters[3] = this._currentAnimation.toProps;
      _mergeObjs(parameters[3], this._currentAnimation.config);
    }
    if (this._currentAnimation.staggerTime) {
      method = 'stagger' + _ucfirst(method);
      _mergeObjs(parameters[2], this._currentAnimation.config);
      parameters.push(this._currentAnimation.staggerTime);
    }
    if (this._currentAnimation.startAfter1 === '__notSetYet__') {
      this._currentAnimation.startAfter1 = this._currentAnimation.startAfter2;
      delete this._currentAnimation.startAfter2;
    }
    if (this._currentAnimation.startAfter1) {
      parameters.push(this._currentAnimation.startAfter1);
    }
    if (!this._currentAnimation.isDisabled) {
      this._animationsQueue.push([parameters, method]);
    }
    this._currentAnimation.startAfter1 = '__notSetYet__';
    return delete this._currentAnimation.staggerTime;
  };
  _startRegisteredAnimations = function(config) {
    var animations, animatorObj, i, inputArr, methodName, tween;
    animations = this._animationsQueue;
    animatorObj = this._gsapObj;
    if (animations.length > 1) {
      animatorObj = new TimelineLite(config);
    }
    i = 0;
    while (i < animations.length) {
      inputArr = animations[i][0];
      methodName = animations[i][1];
      console.log(inputArr, methodName);
      tween = animatorObj[methodName].apply(animatorObj, inputArr);
      i++;
    }
    return tween;
  };
  PrettyGSAP = function() {
    this._gsapObj = TweenLite;
    this._currentAnimation = {};
    this._currentAnimation.isDisabled = false;
    this._currentAnimation.config = {};
    this._animationsQueue = [];
    return this;
  };
  PrettyGSAP.prototype.setElement = function(el) {
    this._currentAnimation.el = el;
    return this;
  };
  PrettyGSAP.prototype.during = function(duration) {
    this._currentAnimation.duration = duration;
    return this;
  };
  PrettyGSAP.prototype.disable = function() {
    this._currentAnimation.isDisabled = true;
    return this;
  };
  PrettyGSAP.prototype.config = function(configObj) {
    return _mergeObjs(this._currentAnimation.config, configObj);
  };
  PrettyGSAP.prototype.to = function(propsObj) {
    if (this._currentAnimation.methodName === 'from') {
      this._currentAnimation.methodName = 'fromTo';
    } else {
      this._currentAnimation.methodName = 'to';
    }
    this._currentAnimation.toProps = propsObj;
    return this;
  };
  PrettyGSAP.prototype.from = function(propsObj) {
    this._currentAnimation.methodName = 'from';
    this._currentAnimation.fromProps = propsObj;
    return this;
  };
  PrettyGSAP.prototype.set = function(props) {
    this._currentAnimation.set = true;
    this._currentAnimation.setProps = props;
    return this;
  };
  PrettyGSAP.prototype.at = function(sec) {
    this._currentAnimation.startAfter1 = this._currentAnimation.startAfter2;
    this._currentAnimation.startAfter2 = sec;
    return this;
  };
  PrettyGSAP.prototype.atLabel = function(label) {
    this.at(label);
    return this;
  };
  PrettyGSAP.prototype.atSecond = function(sec) {
    this.at(sec);
    return this;
  };
  PrettyGSAP.prototype.cycle = function(prop, values) {
    var index;
    index = 2;
    if (this._currentAnimation.methodName === 'fromTo') {
      index++;
    }
    if (!this._currentAnimation[index]['cycle']) {
      this._currentAnimation[index]['cycle'] = {};
    }
    this._currentAnimation[index]['cycle'][prop] = values;
    return this;
  };
  PrettyGSAP.prototype.onUpdate = function(onUpdateHandler) {
    this._currentAnimation.config.onUpdate = onUpdateHandler;
    return this;
  };
  PrettyGSAP.prototype.onComplete = function(completeHandler, params) {
    this._currentAnimation.config.onComplete = completeHandler;
    this._currentAnimation.config.onCompleteParams = params;
    return this;
  };
  PrettyGSAP.prototype.startNow = function() {
    return this.start(0);
  };
  PrettyGSAP.prototype.after = function(sec) {
    return this.start(sec);
  };
  PrettyGSAP.prototype.thenYoyoForever = function(delaySec) {
    if (delaySec == null) {
      delaySec = 0;
    }
    this.thenYoyo(-1, delaySec);
    return this;
  };
  PrettyGSAP.prototype.thenYoyo = function(n, delaySec) {
    if (n == null) {
      n = -1;
    }
    if (delaySec == null) {
      delaySec = 0;
    }
    this.thenRepeat(n, delaySec, true);
    return this;
  };
  PrettyGSAP.prototype.thenRepeat = function(n, delaySec, yoyo) {
    if (delaySec == null) {
      delaySec = 0;
    }
    if (yoyo == null) {
      yoyo = false;
    }
    _setAnimator.call(this, TweenMax);
    this._currentAnimation.config.repeat = n;
    if (delaySec) {
      this.repeatDelay(delaySec);
    }
    if (yoyo) {
      this._currentAnimation.config.yoyo = yoyo;
    }
    return this;
  };
  PrettyGSAP.prototype.repeatDelay = function(sec) {
    this._currentAnimation.config.repeatDelay = sec;
    return this;
  };
  PrettyGSAP.prototype.easeIn = function(easeObj) {
    this.ease(easeObj, 'easeIn');
    return this;
  };
  PrettyGSAP.prototype.easeInOut = function(easeObj) {
    this.ease(easeObj, 'easeInOut');
    return this;
  };
  PrettyGSAP.prototype.easeOut = function(easeObj) {
    this.ease(easeObj, 'easeOut');
    return this;
  };
  PrettyGSAP.prototype.ease = function(easeObj, property) {
    this._currentAnimation.config.ease = easeObj[property];
    return this;
  };
  PrettyGSAP.prototype.stagger = function(stagger) {
    _setAnimator.call(this, TweenMax);
    this._tweenMax = true;
    this._currentAnimation.staggerTime = stagger;
    return this;
  };
  PrettyGSAP.prototype.wait = function(pauseTime) {
    var startAfter;
    if (pauseTime > 0) {
      startAfter = "+=" + pauseTime;
    }
    if (pauseTime < 0) {
      startAfter = "-=" + (pauseTime * -1);
    }
    this._currentAnimation.startAfter1 = this._currentAnimation.startAfter2;
    this._currentAnimation.startAfter2 = startAfter;
    return this;
  };
  PrettyGSAP.prototype.then = function() {
    return this;
  };
  PrettyGSAP.prototype.animate = function(el, disabled) {
    if (disabled == null) {
      disabled = false;
    }
    _registerAnimation.call(this);
    if (disabled) {
      this._currentAnimation.isDisabled = true;
    }
    this._currentAnimation.el = el;
    return this;
  };
  PrettyGSAP.prototype._animate = function(el) {
    return this.animate(el, true);
  };
  _animate = function(el) {
    return animate(el, true);
  };
  animate = function(el, disabled) {
    var animator;
    animator = new PrettyGSAP();
    animator.setElement(el);
    if (disabled) {
      animator.disable();
    }
    return animator;
  };
  PrettyGSAP.prototype.start = function(delay, config) {
    _registerAnimation.call(this);
    return _startRegisteredAnimations.call(this);
  };
  PrettyGSAP.prototype.labelHereAs = function(LabelStr) {
    _registerAnimation.call(this);
    this._currentAnimation.label = LabelStr;
    return this;
  };
  window.animate = animate;
  return window._animate = _animate;
})(window, TweenLite, TweenMax, TimelineLite);

//# sourceMappingURL=pretty-gsap.js.map
